language: node_js
node_js:
- node
dist: trusty
sudo: false
branches:
  only:
  - master
  - develop
cache:
  directories:
  - node_modules
install:
- npm install -g yarn
script:
- yarn --no-progress
- yarn lint
- yarn build --no-progress
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: ZHAEnx6mM/tQNCmYqJf5JFmZNlMx5ZMlFYqzi3u3HeeATTgZ2XbzYqnWpQSSv29oRgXaHQqgQ/anTRfF2zl/Yd6MqYiMubDJGMgonzE5aal5wtlVTm/PzNIykWCa7b6zJCZyoK1OEgOn7bGD7WuIgWikKqfnKiDGavm5YHSQb7yCT1euVO1IDjI0zgapDbl5Dn1P2jhMPcxbzEs2yTGJ+bcfbGUR6BfQsuj8sa0lxRi1iMHtwCgC2C7Fb1AdA4HkGCIiRy7TXna22xP2ZJovbHZqUrIFv9bEv5BLuL4h/nj61W8w2o3vEXcAQPlByae10Wkd8ZIlS1JVJvnTwhCTvcPAIQHHCafWp5gk7nBIPLWgLfyP3pzvdLjfwo/haNhJQs2sUDCR4+5ApyBHlFiEL3ZXlJmWCrTDInEWYwsvZN6GJfD0NFzoWxcD5yycoRsmcWId40VmAZmFfHxkxu0JIxOTuV+bpHIUVZcAXqgkhlr7jzq4cnhUFuuLcHM+YwqqgzuuNH7kjBxvWXvmoMW+MfDJK9mI7RNZIYj6u7IpnrZ1xTOUQ77XEICqp0ZukCyWurx+zOhxT9mJgYZhlQWFppKpYvB08mKE3ira120OCwynSpdQS+VtHOWFUl7kefRkvDv2+zattM3RK7m3nudOYMGJtu7x8+1UpzeARM9hhJ8=
  on:
    branch: master